language: python

sudo: false

matrix:
  fast_finish: true
  include:
  - python: 3.4
    env: TEST_TARGET=default
  - python: 3.5
    env: TEST_TARGET=default
  - python: 3.6
    env: TEST_TARGET=default
  - python: 3.6
    env: TEST_TARGET=docs

env:
  global:
     secure: "n2fDU3WQjw781S8p1qUVAOIbNay991tk0LiiKZkYPJFUxEUT23yA11i/XODKRdoCuLS7gNfBb1P9QWNXQ9liHIRFzCbYRBRvUseHnkAraTBg3Wq2dDikheUQO82S5TMlttmCXJHaqQLdK3YxBqJdc2FitzxqD0/qn9sSmbfTD5MCAymcFWtqRrLyb4PbnmlJvL2EgFQI9AaZq59WDwo04Gw+tDvBn7krb9HQ8ATzw+YVgIO65xk6TXMPqg0NAnkPmYBf4E39ewyeBvPGbgngvk47zWxQ2GO18Au095P+dk6mykmtjsEf68XrobF+bZyz4Em0IcTP8pGeuvkgRhFysNUiW9KXH+UfhIv9MU1Fx4Q/229d2jPYy0xD6IvG9JW9m7bZmBUp6to7uqDnfxnrlxmTKf7CN/M0qpFSIyqXZEfNye4LlvnTOBJh5XkfZnBHLpwptacMlS5m1pjOWYbSUSGUDebqtQTBDaF7g8EcXMkUKw6nMXE1uTvDM7kcSvBNBaVQh5ammZLn2y6rqfZR0NK9vyGGfl1N+axe+U48iRpFBDs3Pq/IeSWvPVajbpR/kIjstu9ybu6qQPq1BlozvbPEuVGNUAja1jAWP/v3YNbJtWl2bWviyLw7/NWC5W95TPLLFUP1p6nqf3AkiZPjpAVmhC2lY1R9CfotSXD0Bo0="

before_install:
  # Install miniconda
  # -----------------
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda
  - wget ${CONDA_BASE}3-3.7.0-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda config --add create_default_packages pip
  - conda update --quiet conda

  # Add 3rd party channels
  # ------------------------------------
  - conda config --add channels conda-forge
  - conda config --add channels axiom-data-science

  # Create our environment
  # ------------------------------------
  - ENV_NAME='test-environment'
  - conda create --quiet -n $ENV_NAME python=$TRAVIS_PYTHON_VERSION
  - source activate $ENV_NAME

  # Install testing requirements
  # ------------------------------------
  - conda install --file requirements.txt --file pocean/tests/requirements.txt
  - conda list --export

# Test source distribution.
install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install pocean-core-${version}.tar.gz && popd

script:
  - set -e

  - if [[ $TEST_TARGET == 'default' ]]; then
      py.test -s -rxs -v ;
    fi

  - if [[ $TEST_TARGET == "docs" ]]; then
      ./docs/deploy.sh ;
    fi
